### ISSUE TITLE
Failed to receive data from URL

### ISSUE THREAD

**Issue by MrCobras** [iLexiconn/LLibrary#178]
Thats crash log, page doesnt work.
https://paste.feed-the-beast.com/view/eb581309

**Comment by Gegy** [comment]
Does this prevent the game from starting, or just it just end up in the logs?

**Comment by MrCobras** [comment]
Game crash on loading mods, i added LLibrrary sources and its working now. But game crashes when i click quit game or alt f4 XD

**Comment by 04Slash** [comment]
Hello Gegy. I had originally saw this issue pop up twice (this being the second user). The first time I had saw it someone people just the 'crash report' section and not the rest of the log leading me to believe this issue had crashed the game. After seeing the log in OP's report I figured it was the same issue, being just a day or two after.

I had since loaded up the game with LLibrary and can confirm that this 'crash' appears in the log, but _does not_ prevent the game from starting. I just forgot to get around to commenting on here that this is likely not the issue.

I apologize for not looking into it further and actually testing if the game would crash with just LLibrary. You're probably good to close this issue. In case it's relevant, [here](https://pastebin.com/nk29yHjE) is the above mentioned log with the 'crash' in it where the game loaded just fine. You can find it on line 431.

**Comment by Ten-jen** [comment]
im also having this issue in 1.12.2 will there be a fix sometime soon? its not causing the game to crash. but it is causing me to be booted from the world immediatly on load (wether it be singleplayer or multiplayer)

**Comment by Brysfal** [comment]
I'm getting repetitive exit code 0 with log only mentionning LLibrary failing to load data from url

https://pastebin.com/QDZ3FUud

p.s. server loads up just fine but client loads up 1/3 times

**Comment by Gegy** [comment]
This is a purely visual issue and won't cause any crashes on its own. As with much of LLibrary, the code is extremely old and very badly designed. This should've never been something that LLibrary would print on failure. This is fixed in https://github.com/iLexiconn/LLibrary/commit/6437a59e2af1edd7e07c9bb4591ea086bd8ad757, and I will be pushing out an update. The fix is not strictly necessary though, because it is not causing any issues on its own, besides printing a misleading crash report.
